In [1]:
import pandas as pd ###Importing pandas

In [2]:
df = pd.read_csv('survey_results_public.csv') ###importing csv files into the code file
schema_df = pd.read_csv('survey_results_schema.csv')

In [3]:
pd.set_option('display.max_columns', 85)
pd.set_option('display.max_rows', 85)

In [4]:
df.shape ###checks how many rows and columns

(83439, 48)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83439 entries, 0 to 83438
Data columns (total 48 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ResponseId                    83439 non-null  int64
 1   MainBranch                    83439 non-null  object
 2   Employment                    83323 non-null  object
 3   Country                       83439 non-null  object
 4   US_State                      14920 non-null  object
 5   UK_Country                    4418 non-null   object
 6   EdLevel                       83126 non-null  object
 7   Age1stCode                    83243 non-null  object
 8   LearnCode                     82963 non-null  object
 9   YearsCode                     81641 non-null  object
 10  YearsCodePro                  61216 non-null  object
 11  DevType                       66484 non-null  object
 12  OrgSize                       60726 non-null  object
 13  Currency                      61080 non-null  object
 14  CompTotal                     47183 non-null  float64
 15  CompFreq                      52150 non-null  object
 16  LanguageHaveWorkedWith        82357 non-null  object
 17  LanguageWantToWorkWith        76821 non-null  object
 18  DatabaseHaveWorkedWith        69546 non-null  object
 19  DatabaseWantToWorkWith        58299 non-null  object
 20  PlatformHaveWorkedWith        52135 non-null  object
 21  PlatformWantToWorkWith        41619 non-null  object
 22  WebframeHaveWorkedWith        61707 non-null  object
 23  WebframeWantToWorkWith        52095 non-null  object
 24  MiscTechHaveWorkedWith        47055 non-null  object
 25  MiscTechWantToWorkWith        38021 non-null  object
 26  ToolsTechHaveWorkedWith       72537 non-null  object
 27  ToolsTechWantToWorkWith       65480 non-null  object
 28  NEWCollabToolsHaveWorkedWith  81234 non-null  object
 29  NEWCollabToolsWantToWorkWith  73022 non-null  object
 30  OpSys                         83294 non-null  object
 31  NEWStuck                      83052 non-null  object
 32  NEWSOSites                    83171 non-null  object
 33  SOVisitFreq                   82413 non-null  object
 34  SOAccount                     82525 non-null  object
 35  SOPartFreq                    67553 non-null  object
 36  SOComm                        82319 non-null  object
 37  NEWOtherComms                 82828 non-null  object
 38  Age                           82407 non-null  object
 39  Gender                        82286 non-null  object
 40  Trans                         80678 non-null  object
 41  Sexuality                     73366 non-null  object
 42  Ethnicity                     79464 non-null  object
 43  Accessibility                 77603 non-null  object
 44  MentalHealth                  76920 non-null  object
 45  SurveyLength                  81711 non-null  object
 46  SurveyEase                    81948 non-null  object
 47  ConvertedCompYearly           46844 non-null  float64
dtypes: float64(2), int64(1), object(45)
memory usage: 30.6+ MB

In [6]:
schema_df

,qid,qname,question,force_resp,type,selector
0,QID16,S0,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB
1,QID12,MetaInfo,Browser Meta Info,False,Meta,Browser
2,QID1,S1,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
3,QID2,MainBranch,Which of the following options best describes ...,True,MC,SAVR
4,QID24,Employment,Which of the following best describes your cur...,False,MC,MAVR
5,QID6,Country,"Where do you live? <span style=""font-weight: b...",True,MC,DL
6,QID7,US_State,<p>In which state or territory of the USA do y...,False,MC,DL
7,QID9,UK_Country,In which part of the United Kingdom do you liv...,False,MC,DL
8,QID190,S2,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
9,QID25,EdLevel,Which of the following best describes the high...,False,MC,SAVR
10,QID149,Age1stCode,At what age did you write your first line of c...,False,MC,MAVR
11,QID276,LearnCode,How did you learn to code? Select all that apply.,False,MC,MAVR
12,QID32,YearsCode,"Including any education, how many years have y...",False,MC,DL
13,QID34,YearsCodePro,"NOT including education, how many years have y...",False,MC,DL
14,QID31,DevType,Which of the following describes your current ...,False,MC,MAVR
15,QID29,OrgSize,Approximately how many people are employed by ...,False,MC,MAVR
16,QID50,Currency,Which currency do you use day-to-day? If your ...,True,MC,SB
17,QID51,CompTotal,What is your current total compensation (salar...,False,TE,SL
18,QID52,CompFreq,"Is that compensation weekly, monthly, or yearly?",False,MC,MAVR
19,QID61,S3,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
20,QID233,Language,"Which <b>programming, scripting, and markup la...",False,Matrix,Likert
21,QID262,Database,Which <b>database environments </b>have you do...,False,Matrix,Likert
22,QID263,Platform,Which <b>cloud platforms</b> have you done ext...,False,Matrix,Likert
23,QID264,Webframe,Which <strong>web frameworks </strong><span st...,False,Matrix,Likert
24,QID265,MiscTech,Which <b>other frameworks and libraries</b> ha...,False,Matrix,Likert
25,QID275,ToolsTech,Which <strong>tools</strong> have you done ext...,False,Matrix,Likert
26,QID274,NEWCollabTools,Which <strong>development environments</strong...,False,Matrix,Likert
27,QID71,OpSys,What is the primary operating system in which ...,False,MC,SAVR
28,QID243,NEWStuck,What do you do when you get stuck on a problem...,False,MC,MAVR
29,QID91,S4,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
30,QID266,NEWSOSites,Which of the following Stack Overflow sites ha...,False,MC,MAVR
31,QID100,SOVisitFreq,How frequently would you say you visit Stack O...,False,MC,MAVR
32,QID101,SOAccount,Do you have a Stack Overflow account?,False,MC,MAVR
33,QID102,SOPartFreq,How frequently would you say you participate i...,False,MC,MAVR
34,QID106,SOComm,Do you consider yourself a member of the Stack...,False,MC,MAVR
35,QID267,NEWOtherComms,Are you a member of any other online developer...,False,MC,MAVR
36,QID268,NEWOtherCommsNames,Please name up to 5 other online developer com...,False,Matrix,Likert
37,QID121,S5,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
38,QID127,Age,What is your age?,False,MC,MAVR
39,QID122,Gender,"Which of the following describe you, if any? P...",False,MC,MAVR
40,QID153,Trans,Do you identify as transgender?,False,MC,MAVR
41,QID136,Sexuality,"Which of the following describe you, if any? P...",False,MC,MAVR
42,QID126,Ethnicity,"Which of the following describe you, if any? P...",False,MC,MAVR
43,QID124,Accessibility,"Which of the following describe you, if any? P...",False,MC,MAVR
44,QID125,MentalHealth,"Which of the following describe you, if any? P...",False,MC,MAVR
45,QID131,S6,"<span style=""font-size:22px;""><strong>Final Qu...",False,DB,TB
46,QID132,SurveyLength,How do you feel about the length of the survey...,False,MC,MAVR
47,QID133,SurveyEase,How easy or difficult was this survey to compl...,False,MC,MAVR

In [7]:
high_sal = (df['CompTotal'] > 70000) & (df['LanguageHaveWorkedWith'] == 'Python') & df['LearnCode'].str.contains("Coding Bootcamp", na=False)

In [8]:
df.loc[high_sal]

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,DevType,OrgSize,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSys,NEWStuck,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,NEWOtherComms,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
1475,1476,I am a developer by profession,Employed full-time,United States of America,Pennsylvania,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,Coding Bootcamp;School;Online Courses or Certi...,5,5,"Developer, back-end","1,000 to 4,999 employees",USD\tUnited States dollar,140000.0,Yearly,Python,Python,DynamoDB;MariaDB;MongoDB;MySQL;PostgreSQL;Redi...,PostgreSQL;Redis,AWS;DigitalOcean;Google Cloud Platform,AWS,Flask,Flask,NumPy;Pandas;TensorFlow;Torch/PyTorch,Hadoop;NumPy;Pandas,Docker;Git;Terraform,Docker;Git,IPython/Jupyter;PyCharm;Visual Studio,IPython/Jupyter;PyCharm;Visual Studio Code,MacOS,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,A few times per week,Yes,A few times per month or weekly,Neutral,No,45-54 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a mood or emotional disorder (e.g. depr...,Appropriate in length,Easy,140000.0
6449,6450,I am a developer by profession,Employed full-time,Germany,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,Coding Bootcamp;Books / Physical media,28,23,"Developer, desktop or enterprise applications;...","10,000 or more employees",EUR European Euro,84000.0,Yearly,Python,Clojure;LISP;Python,NaN,NaN,AWS,AWS,Flask,FastAPI;Flask,NaN,NaN,Docker;Kubernetes,NaN,Emacs;IPython/Jupyter,Emacs;IPython/Jupyter,Linux-based,Call a coworker or friend;Go for a walk or oth...,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,Less than once per month or monthly,"No, not really",Yes,45-54 years old,NaN,Prefer not to say,NaN,NaN,NaN,NaN,Too long,NaN,90802.0
13928,13929,I am a developer by profession,Employed full-time,India,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,4,3,Data scientist or machine learning specialist,"1,000 to 4,999 employees",INR\tIndian rupee,3500000.0,Yearly,Python,Scala,NaN,NaN,AWS,AWS,NaN,NaN,Apache Spark,Apache Spark;TensorFlow;Torch/PyTorch,Git,Git,IntelliJ;Sublime Text,IntelliJ,Linux-based,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,Multiple times per day,Not sure/can't remember,NaN,Neutral,No,25-34 years old,Man,No,NaN,South Asian,None of the above,None of the above,Appropriate in length,Easy,48866.0
14028,14029,I am a developer by profession,Employed full-time,Norway,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,3,2,DevOps specialist,"10,000 or more employees",NOK\tNorwegian krone,550000.0,Yearly,Python,Bash/Shell;Go,SQLite,Redis,NaN,NaN,NaN,NaN,NaN,NaN,Git,Ansible;Docker;Git;Kubernetes;Terraform,Visual Studio Code,Vim;Visual Studio Code,Linux-based,Call a coworker or friend;Go for a walk or oth...,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per week,"Yes, somewhat",No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,59342.0
22117,22118,I am a developer by profession,Employed full-time,Thailand,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,Coding Bootcamp;Other online resources (ex: vi...,6,2,Data scientist or machine learning specialist,100 to 499 employees,THB\tThai baht,115000.0,Monthly,Python,Python,MySQL,MySQL,Google Cloud Platform,Google Cloud Platform,NaN,NaN,NumPy;Pandas,NumPy;Pandas;Torch/PyTorch,Git,Git,PyCharm,PyCharm,Linux-based,Visit Stack Overflow;Google it,Stack Overflow;Stack Exchange,Multiple times per day,Yes,A few times per month or weekly,"Yes, definitely",No,25-34 years old,Man,No,Straight / Heterosexual,South Asian,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,44208.0
25011,25012,I am a developer by profession,Employed full-time,India,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,Coding Bootcamp;Other online resources (ex: vi...,8,4,"Engineer, data;DevOps specialist;Engineer, sit...",100 to 499 employees,INR\tIndian rupee,2100000.0,Yearly,Python,Scala,Cassandra;Elasticsearch;MongoDB,Cassandra;Elasticsearch;MongoDB,AWS,AWS;Google Cloud Platform;Microsoft Azure,NaN,NaN,Hadoop,Flutter;Hadoop,Docker;Git,Ansible;Docker;Kubernetes;Terraform,PyCharm;Vim,Android Studio;PyCharm;Vim,Linux-based,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,Less than once per month or monthly,"Yes, somewhat",No,25-34 years old,Man,No,Straight / Heterosexual,I don't know,None of the above,None of the above,Appropriate in length,Easy,29320.0
31283,31284,"I am not primarily a developer, but I write co...",Employed full-time,India,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",5 - 10 years,Coding Bootcamp;Other online resources (ex: vi...,15,1,Data or business analyst,20 to 99 employees,INR\tIndian rupee,600000.0,Yearly,Python,F#;JavaScript,MySQL,NaN,Google Cloud Platform;Heroku;Microsoft Azure,NaN,FastAPI,NaN,NumPy;Pandas,TensorFlow;Torch/PyTorch,Git,Docker,IPython/Jupyter;Visual Studio Code,Vim,Windows,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,A few times per week,Yes,Less than once per month or monthly,"No, not really",No,18-24 years old,Man,No,Straight / Heterosexual,South Asian,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,8377.0
32543,32544,I am a developer by profession,Employed full-time,Russian Federation,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,Coding Bootcamp;Other online resources (ex: vi...,5,4,"Developer, back-end",20 to 99 employees,RUB\tRussian ruble,226000.0,Monthly,Python,Haskell;Node.js,MongoDB;PostgreSQL;Redis,NaN,NaN,NaN,Django;FastAPI;Flask,React.js;Vue.js,NaN,NaN,Docker;Git,Kubernetes,Vim,NaN,MacOS,Visit Stack Overflow;Google it;Panic,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,Neutral,No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Too short,Easy,42648.0
35406,35407,I am a developer by profession,Employed full-time,United States of America,Ohio,NaN,Something else,25 - 34 years,Coding Bootcamp;Other online resources (ex: vi...,5,4,DevOps specialist,100 to 499 employees,USD\tUnited States dollar,97000.0,Yearly,Python,Python;Ruby,Elasticsearch;PostgreSQL,PostgreSQL,AWS,AWS,Flask,Ruby on Rails,NaN,NaN,Ansible;Docker;Git,Ansible;Docker;Git;Terraform,Visual Studio Code,Visual Studio Code,MacOS,Call a coworker or friend;Google it,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,Less than once per month or monthly,Neutral,No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,97000.0
39985,39986,I am a developer by profession,Employed full-time,India,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,3,2,"Developer, back-end",500 to 999 employees,INR\tIndian rupee,1200000.0,Yearly,Python,Go;JavaScript,Elasticsearch;MongoDB;PostgreSQL;Redis,Cassandra;Couchbase;DynamoDB,NaN,NaN,Django;FastAPI,FastAPI;Vue.js,NaN,NaN,Docker;Git,Docker;Git;Kubernetes,Visual Studio Code,Visual Studio Code,MacOS,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,"No, not really",No,25-34 years old,Man,No,Straight / Heterosexual,South Asian,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,16754.0
43588,43589,I am a developer by profession,Employed full-time,Pakistan,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,6,2,"Developer, full-stack;Developer, back-end",100 to 499 employees,PKR\tPakistani rupee,1000000.0,Yearly,Python,TypeScript,Elasticsearch;MySQL;Redis;SQLite,NaN,DigitalOcean;Heroku,AWS,Django;Flask;jQuery;React.js,Django;React.js,Flutter;React Native,React Native,Docker;Git,NaN,PyCharm;Visual Studio Code,NaN,Linux-based,Visit Stack Overflow;Google it;Do other work a...,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,Less than once per month or monthly,"Yes, definitely",Yes,18-24 years old,Man,No,Straight / Heterosexual,East Asian,None of the above,I have a mood or emotional disorder (e.g. depr...,Appropriate in length,Easy,6485.0
49498,49499,I am a developer by profession,Employed full-time,Viet Nam,NaN,NaN,Some college/university study without earning ...,18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,3,2,"Engineer, data;Data scientist or machine learn...",100 to 499 employees,VND\tVietnamese dong,16500000.0,Monthly,Python,Go;Java;Python,MySQL;PostgreSQL;Redis,Cassandra;Elasticsearch;Microsoft SQL Server;M...,NaN,NaN,Flask,FastAPI,Apache Spark;NumPy;Pandas,TensorFlow;Torch/PyTorch,Git,Docker,PyCharm,Vim,Windows,Go for a walk or other physical activity;Googl...,Stack Overflow,Multiple times per day,No,NaN,"No, not at all",Yes,18-24 years old,Man,No,Straight / Heterosexual,Southeast Asian,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,8544.0
53009,53010,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Indonesia,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,Coding Bootcamp;Other online resources (ex: vi...,7,Less than 1 year,"Developer, desktop or enterprise applications;...","Just me - I am a freelancer, sole proprietor, ...",IDR\tIndonesian rupiah,50000000.0,Yearly,Python,Python,Firebase;MySQL;PostgreSQL;SQLite,PostgreSQL;SQLite,Heroku,Heroku,Django,Django,NaN,NaN,Git,Git,Visual Studio Code,Visual Studio Code,MacOS,Go for a walk or other physical activity;Googl...,Stack Overflow,Daily or almost daily,Not sure/can't remember,NaN,Neutral,No,25-34 years old,Man,No,Straight / Heterosexual,Southeast Asian,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,3659.0
53346,53347,I am a developer by profession,Employed full-time,India,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,5,3,"Developer, full-stack","10,000 or more employees",INR\tIndian rupee,85000.0,Monthly,Python,Python,PostgreSQL,MongoDB;Oracle;PostgreSQL,NaN,NaN,Angular.js,Django;Flask,NaN,NaN,Git,Git,PyCharm;Vim,PyCharm;Vim,Linux-based,Visit Stack Overflow;Google it,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per month or weekly,"Yes, definitely",Yes,25-34 years old,Man,No,Straight / Heterosexual,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,14244.0
53702,53703,I am a developer by profession,Employed full-time,India,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",18 - 24 years,Coding Bootcamp;Friend or family member;Colleague,10,7,"Developer, back-end",500 to 999 employees,INR\tIndian rupee,1300000.0,Yearly,Python,Python,MySQL,Elasticsearch;MongoDB;MySQL;PostgreSQL;Redis,AWS,AWS;Google Cloud Platform,Django,Django;FastAPI;React.js,NaN,NaN,NaN,NaN,Sublime Text,IPython/Jupyter;Sublime Text,Other (please specify):,Google it,Stack Overflow,A few times per week,Not sure/can't remember,NaN,"Yes, somewhat",Yes,25-34 years old,Man,No,NaN,I don't know,None of the above,NaN,Too long,Neither easy nor difficult,18150.0
55701,55702,I am a developer by profession,Employed full-time,United States of America,New York,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,Coding Bootcamp,7,6,"Developer, back-end;Student",100 to 499 employees,USD\tUnited States dollar,160000.0,Yearly,Python,NaN,MySQL,NaN,Google Cloud Platform,NaN,Flask,NaN,NaN,NaN,Docker;Kubernetes,NaN,Sublime Text,NaN,MacOS,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,A few times per week,Not sure/can't remember,NaN,"No, not at all",No,25-34 years old,Woman,No,Prefer not to say,Southeast Asian;East Asian,None of the above,I have a mood or emotional disorder (e.g. depr...,Appropriate in length,Neither easy nor difficult,160000.0
57623,57624,I am a developer by profession,Employed full-time,Pakistan,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,14,7,"Developer, back-end",20 to 99 employees,PKR\tPakistani rupee,137000.0,Monthly,Python,Java;JavaScript;Kotlin;Python;SQL,PostgreSQL,PostgreSQL,AWS,AWS,NaN,NaN,Keras;NumPy;Pandas;TensorFlow,Keras;NumPy;Pandas;React Native;TensorFlow;Tor...,Git,Docker;Git,Notepad++;PyCharm,Android Studio,Windows,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,A few times per month or weekly,Yes,Less than once per month or monthly,"Yes, definitely",Yes,25-34 years old,Man,No,Straight / Heterosexual,South Asian,None of the above,None of the above,Appropriate in length,Easy,10656.0
63735,63736,"I am not primarily a developer, but I write co...",Employed full-time,United States of America,Maryland,NaN,Some college/university study without earning ...,11 - 17 years,Coding Bootcamp;Other online resources (ex: vi...,15,15,Other (please specify):,"10,000 or more employees",USD\tUnited States dollar,375000.0,Yearly,Python,C;Python,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Chef;Git,Ansible;Git,Notepad++;Vim;Visual Studio Code,Vim;Visual Studio Code,Linux-based,Call a coworker or friend;Go for a walk or oth...,Stack Overflow;Stack Exchange,A few times per week,Yes,Less than once per month or monthly,"Yes, somewhat",Yes,35-44 years old,Man,No,Straight / Heterosexual,Middle Eastern,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,375000.0
65842,65843,I am a developer by profession,Employed full-time,Indonesia,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,Coding Bootcamp;School;Online Forum;Friend or ...,6,2,"Developer, back-end",10 to 19 employees,IDR\tIndonesian rupiah,8000000.0,Monthly,Python,Rust,MariaDB;MongoDB;PostgreSQL;Redis;SQLite,NaN,NaN,NaN,Django;FastAPI;Flask,Django;FastAPI,NaN,NaN,Git,Docker;Kubernetes;Yarn,PyCharm;Visual Studio Code,NaN,Windows Subsystem for Linux (WSL),Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,Neutral,Yes,18-24 years old,Man,No,Straight / Heterosexual,Southeast Asian,None of the above,None of the above,Appropriate in length,Easy,7020.0
72911,72912,"I am not primarily a developer, but I write co...",Employed full-time,Germany,NaN,NaN,"Other doctoral degree (Ph.D., Ed.D., etc.)",18 - 24 years,Coding Bootcamp;Books / Physical media,30,20,Other (please specify):,"5,000 to 9,999 employees",EUR European Euro,120000.0,Yearly,Python,JavaScript;Julia;Python,NaN,NaN,NaN,NaN,NaN,NaN,NumPy;Pandas,NumPy;Pandas;Torch/PyTorch,NaN,NaN,IPython/Jupyter;PyCharm,IPython/Jupyter;PyCharm,MacOS,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow,A few times per week,Yes,A few times per month or weekly,"Yes, definitely",Yes,55-64 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,129718.0
73256,73257,I am a developer by profession,Employed full-time,India,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,9,3,"Developer, back-end","10,000 or more employees",INR\tIndian rupee,476000.0,Yearly,Python,Python,MySQL;PostgreSQL;SQLite,NaN,NaN,NaN,Django,NaN,NumPy;Pandas,NumPy;Pandas,NaN,NaN,IPython/Jupyter;Sublime Text;Visual Studio Code,IPython/Jupyter;PyCharm;Sublime Text;Visual St...,Linux-based,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Less than once per month or monthly,"Yes, definitely",No,25-34 years old,Man,No,Straight / Heterosexual,South Asian,None of the above,None of the above,Appropriate in length,Easy,6646.0
74167,74168,I am a developer by profession,Employed full-time,India,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,Coding Bootcamp;School;Online Courses or Certi...,9,6,"Developer, desktop or enterprise applications;...","10,000 or more employees",INR\tIndian rupee,1600000.0,Yearly,Python,Go;JavaScript;Python;TypeScript,DynamoDB,DynamoDB;MongoDB;Redis,AWS;Heroku,AWS;Heroku,Flask,Express;FastAPI;React.js,Pandas,Pandas,Git,Docker;Git;Kubernetes;Terraform,IntelliJ;Notepad++;Visual Studio;Visual Studio...,Notepad++;Visual Studio Code,Windows,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Overflow for Teams (priva...,A few times per month or weekly,Yes,Less than once per month or monthly,Neutral,Yes,25-34 years old,Man,No,Straight / Heterosexual,South Asian,None of the above,None of the above,Appropriate in length,Easy,22339.0

In [9]:
df.rename(columns={'RESPONSEID': 'Response', 'COUNTRY': 'PlaceOfResidence'}, inplace=True) ###renaming columns

In [10]:
df.loc[1475, ['EMPLOYMENT', 'LEARNCODE']] = ['PUMPKINS', 'CHICKENS'] ###changing the employment and learncode row values to pumpkins and chickens

In [11]:
df.loc[1475, 'EMPLOYMENT'] = 'CHEESE' ###changing the employment row of the response at 1475 to 'CHEESE'

In [12]:
df['EMPLOYMENT'].map({'Employed full-time': 'Bobs'}) ###this changes all answers of "Employed full-time" in the Employment column to "Bobs"

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ...
83434    NaN
83435    NaN
83436    NaN
83437    NaN
83438    NaN
Name: EMPLOYMENT, Length: 83439, dtype: object

In [13]:
df['Working-Where'] = df['EMPLOYMENT'] + ' ' + df['PlaceOfResidence'] ###Creating a new column called Working-where that includes country and type of employment

KeyError: 'PlaceOfResidence'

In [ ]:
df.drop(columns=['SEXUALITY', 'ACCESSIBILITY']) ###Dropping the sexuality and accessibility columns

In [ ]:
df['Working-Where'].str.split(' ', expand=True)

In [ ]:
df.append({'first': 'Tony'}, ignore_index=True) ###Appending a single row of data

In [ ]:
df.sort_values(by='EMPLOYMENT', ascending=False)

In [ ]:
df.sort_values(by=['Country', 'CompTotal'], ascending=[True, False], inplace=True) ###Sorting values by Country and CompTotal, and setting Country to Aplhabetical ascending order

In [ ]:
df

In [ ]:
df['CompTotal'].head(10)

In [ ]:
df['CompTotal'].median() ###Pulls median from the CompTotal column

In [ ]:
df.median() ###Pulls median for all numerical values in the dataframe

In [ ]:
df.describe() ###50% is the median quantile

In [ ]:
df['CompTotal'].count()

In [ ]:
df['Trans'].value_counts(normalize=True)

In [ ]:
##Group-by is done by splitting, combining, and grouping

In [ ]:
df['Country'].value_counts()

In [17]:
country_grp = df.groupby(['Country'])

In [19]:
country_grp.get_group('India')

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,DevType,OrgSize,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSys,NEWStuck,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,NEWOtherComms,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly,EMPLOYMENT,LEARNCODE
8,9,I am a developer by profession,Employed part-time,India,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,Coding Bootcamp,6,4,"Developer, front-end","10,000 or more employees",INR\tIndian rupee,NaN,Monthly,HTML/CSS;JavaScript,HTML/CSS;JavaScript,PostgreSQL,PostgreSQL,AWS,NaN,Django;FastAPI,Django;FastAPI,NaN,NaN,Docker;Git,Docker;Git;Kubernetes,PyCharm;Sublime Text,PyCharm;Sublime Text,Windows,Visit Stack Overflow;Google it;Panic,Stack Overflow;Stack Exchange,A few times per week,Yes,Less than once per month or monthly,"Yes, definitely",No,25-34 years old,Man,No,NaN,South Asian,NaN,I have a concentration and/or memory disorder ...,Appropriate in length,Easy,NaN,NaN,NaN
22,23,I am a student who is learning to code,"Student, full-time",India,NaN,NaN,Some college/university study without earning ...,5 - 10 years,School;Friend or family member,7,NaN,NaN,NaN,NaN,NaN,NaN,C#;HTML/CSS;Python,Java;Kotlin;Python,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unity 3D,NaN,Android Studio,Android Studio,Windows,Visit Stack Overflow;Google it;Watch help / tu...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,"Yes, definitely",No,Under 18 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN,NaN,NaN
39,40,I am a student who is learning to code,"Student, part-time",India,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,School,3,NaN,NaN,NaN,NaN,NaN,NaN,C;C#;C++;HTML/CSS;JavaScript;Node.js;Python,NaN,MongoDB,NaN,Heroku,NaN,Express;jQuery;React.js,NaN,Keras;NumPy;TensorFlow,NaN,Flow;Unity 3D,NaN,IPython/Jupyter;Sublime Text;Visual Studio Code,NaN,Linux-based,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,A few times per month or weekly,"Yes, somewhat",Yes,18-24 years old,Woman,No,Straight / Heterosexual,White or of European descent,None of the above,I have a concentration and/or memory disorder ...,Appropriate in length,Easy,NaN,NaN,NaN
49,50,I am a student who is learning to code,"Student, full-time",India,NaN,NaN,Some college/university study without earning ...,11 - 17 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C;HTML/CSS;Java;JavaScript;Kotlin;Node.js;Pyth...,Dart;Elixir;Go;SQL,NaN,NaN,Heroku,NaN,Django;Express;React.js,Angular,NaN,NaN,Git;Yarn,NaN,Android Studio;Atom;Notepad++;Sublime Text;Vis...,NaN,Windows,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow,Multiple times per day,Yes,A few times per week,"Yes, definitely",No,18-24 years old,Man,No,Straight / Heterosexual,South Asian,None of the above,None of the above,Appropriate in length,Easy,NaN,NaN,NaN
52,53,I am a developer by profession,Employed full-time,India,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",5,4,"Developer, full-stack","1,000 to 4,999 employees",INR\tIndian rupee,NaN,NaN,HTML/CSS;JavaScript;Node.js;Python;TypeScript,HTML/CSS;JavaScript;Node.js;PowerShell;Python;...,Firebase;MongoDB;Redis,DynamoDB;Elasticsearch;Firebase;MongoDB;Redis,AWS;DigitalOcean;Heroku;Microsoft Azure;Oracle...,AWS;DigitalOcean;Google Cloud Platform;Heroku;...,Angular;Express;React.js,Angular;Express;React.js,Cordova,Cordova,Docker;Git;Kubernetes,Docker;Git;Kubernetes,Visual Studio Code;Xcode,Visual Studio Code;Xcode,MacOS,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow,Multiple times per day,Yes,Less than once per month or monthly,"Yes, definitely",No,25-34 years old,Man,No,Prefer not to say,I don't know,None of the above,None of the above,Too long,Neither easy nor difficult,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83399,83400,I am a developer by profession,Employed full-time,India,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,6,"Developer, front-end",20 to 99 employees,INR\tIndian rupee,2000000.0,Yearly,HTML/CSS;JavaScript;TypeScript,JavaScript;Node.js,NaN,NaN,AWS;Microsoft Azure,AWS,Angular;React.js,Gatsby;React.js;Svelte;Vue.js,React Native,NaN,Git;Yarn,Git;Yarn,Vim;Visual Studio Code,Vim;Visual Studio Code;Webstorm,MacOS,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per week,"Yes, definitely",No,25-34 years old,Man,No,Straight / Heterosexual,South Asian,None of the above,None of the above,Too short,Easy,27923.0,NaN,NaN
83406,83407,I am a student who is learning to code,"Student, full-time",India,NaN,NaN,"Secondary school (e.g. American high school, G...",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",2,NaN,NaN,NaN,NaN,NaN,NaN,C;C++;Python,C;C#;C++;HTML/CSS;JavaScript;Python;Rust;SQL;T...,MySQL,MySQL;Oracle,NaN,NaN,NaN,NaN,NumPy,.NET Framework;Flutter;NumPy;React Native;Tens...,Git,Deno;Docker;Git,PyCharm;Visual Studio Code,NaN,Windows,Visit Stack Overflow;Google it;Do other work a...,Stack Overflow;Stack Exchange,A few times per month or weekly,Yes,I have never participated in Q&A on Stack Over...,"No, not really",Yes,18-24 years old,Man,No,Straight / Heterosexual,South Asian,None of the above,None of the above,Appropriate in length,Easy,NaN,NaN,NaN
83410,83411,I am a student who is learning to code,"Student, part-time",India,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,"Other online resources (ex: videos, blogs, etc)",1,NaN,NaN,NaN,NaN,NaN,NaN,C++;JavaScript;Python;TypeScript,C++;JavaScript;Python;TypeScript,MongoDB;PostgreSQL;SQLite,MongoDB;PostgreSQL;SQLite,Heroku,Heroku,Express;React.js,Express;React.js,Keras;NumPy;TensorFlow,Keras;NumPy;TensorFlow,Docker;Git;Unreal Engine,Docker;Git;Unreal Engine,Android Studio;Atom;Eclipse;IntelliJ;IPython/J...,IPython/Jupyter;PyCharm;Vim;Visual Studio;Visu...,Windows,Google it;Panic,Stack Overflow;Stack Exchange,Multiple times per day,Yes,I have never participated in Q&A on Stack Over...,"Yes, definitely",No,18-24 years old,Man,No,Straight / Heterosexual,I don't know,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,NaN,NaN,NaN
83411,83412,I am a developer by profession,Employed full-time,India,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",8,5,"Developer, back-end",100 to 499 employees,INR\tIndian rupee,3500000.0,Yearly,Java;JavaScript;SQL,Go;Java;Kotlin;Node.js;SQL,MySQL,Cassandra;Elasticsearch;Redis,AWS,AWS;Google Cloud Platform,Spring,Spring,NaN,NaN,Docker;Git,Ansible;Docker;Git;Kubernetes;Terraform,Eclipse;Sublime Text;Visual Studio Code,Eclipse;IntelliJ;Sublime Text,MacOS,Visit Stack Overflow;Google it;Watch help / tu...,Stack Overflow;Stack Exchange;Stack Overflow f...,Daily or almost daily,Yes,Less than once per month or monthly,"Yes, somewhat",No,25-34 years old,Man,No,Straight / Heterosexual,South Asian,None of the above,None of the above,Appropriate in length,Easy,48866.0,NaN,NaN
83417,83418,I am a developer by profession,"Student, full-time",India,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,School;Friend or family member;Online Courses ...,3,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell;C;C++;Java;SQL,Bash/Shell;C++;SQL,PostgreSQL;SQLite,PostgreSQL,AWS,Google Cloud Platform;Microsoft Azure,Spring,jQuery;Spring,NaN,NaN,Docker;Git,Docker;Git,IntelliJ;Vim;Visual Studio Code,IntelliJ;Vim;Visual Studio Code,Linux-based,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow;Stack Exchange;Stack Overflow f...,Multiple times per day,Yes,Daily or almost daily,"Yes, definitely",Yes,18-24 years old,Man,No,NaN,South Asian,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN,NaN,NaN

In [ ]:
filt = df['Country'] == 'Germany' ###Running a filter to find country of choice...
df.loc[filt]['Trans'].value_counts() ###then counting the value of responses to the Trans question in the survey

In [ ]:
country_grp['LearnCode'].value_counts().loc['United States of America'].head(20)

In [ ]:
country_grp['CompTotal'].agg(['median', 'mean']).loc['United States of America']